### PR TITLE
fix: Graph builder errors when invalid type is given

### LINKED ISSUE #47: `graph_builder()` needs to fail with invalid `type`?
``` r
library(orbweaver)

# Should this trigger an error?
graph_builder(type = "bad")
#> <pointer: 0x62459120a500>
#> attr(,"class")
#> [1] "DirectedGraphBuilder"

# Do we need to enumerate valid options in the signature and use match.arg()?
# https://design.tidyverse.org/enumerate-options.html#whats-the-pattern
formals(graph_builder)
#> $type
#> [1] "directed"
```

<sup>Created on 2025-02-28 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

### PR DESCRIPTION
**Pull request by andyquinterom**
* Closes #47

### CODE REVIEW

File: R/builder.R [hunk 1]
```diff
@@ -7,7 +7,8 @@
 #' @examples
 #' graph_builder()
 graph_builder <- function(type = "directed") {
-  DirectedGraphBuilder$new()
+  if (type == "directed") return(DirectedGraphBuilder$new())
+  rlang::abort("orbweaver currently supports the following types: `directed`")
 }
```
Comment (mauro-ixpantia) [inline R/builder.R]: Consider this simpler pattern

https://design.tidyverse.org/enumerate-options.html#whats-the-pattern

``` r
f <- function(type = c("directed", "undirected")) {
  match.arg(type)
}

f()
#> [1] "directed"
f("directed")
#> [1] "directed"
f("bad")
#> Error in match.arg(type): 'arg' should be one of "directed", "undirected"

# Using rlang
g <- function(type = c("directed", "undirected")) {
  rlang::arg_match(type)
}

g("bad")
#> Error in `g()`:
#> ! `type` must be one of "directed" or "undirected", not "bad".
```

<sup>Created on 2025-03-06 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

File: DESCRIPTION [hunk 2]
```diff
@@ -1,6 +1,6 @@
 Package: orbweaver
 Title: Fast and Efficient Graph Data Structures
-Version: 0.18.0
+Version: 0.18.2
```
Comment (mauro-ixpantia) [inline DESCRIPTION:3]: Looks like it comes from another PR https://github.com/ixpantia/orbweaver-r/pull/61

image

**Review by mauro-ixpantia — APPROVED** [review]
LGTM but see my comments. Good to go once you've consider them.
